apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipment-platform.api.fullname" . }}
  labels:
    {{- include "shipment-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "shipment-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
