"""add users table

Revision ID: 993bce92ce6c
Revises: e1a73d5cd9c8
Create Date: 2026-10-06 19:15:16.159048
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '993bce92ce6c'
down_revision: Union[str, None] = 'e1a73d5cd9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    _seed_users()
    # ### end Alembic commands ###



# Seeded development users (PLAN.md §27 roles).
# Local development defaults only: replace via an admin flow in production.
_DEFAULT_USERS = (
    ("developer", "developer", "developer"),
    ("release_manager", "release_manager", "release_manager"),
    ("admin", "admin", "admin"),
)


def _seed_users() -> None:
    import uuid

    import bcrypt

    users = sa.table(
        "users",
        sa.column("id", sa.Uuid),
        sa.column("username", sa.String),
        sa.column("password_hash", sa.String),
        sa.column("role", sa.String),
        sa.column("is_active", sa.Boolean),
    )
    for username, password, role in _DEFAULT_USERS:
        pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
        op.execute(
            users.insert().values(
                id=uuid.uuid4(),
                username=username,
                password_hash=pw_hash,
                role=role,
                is_active=True,
            ).on_conflict_do_nothing(index_elements=["username"])
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
