"""initial shipment schema

Revision ID: e1a73d5cd9c8
Revises: 
Create Date: 2026-10-06 15:41:23.030968
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'e1a73d5cd9c8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('artifact_name', sa.String(length=512), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product', 'version', name='uq_shipments_product_version')
    )
    op.create_index(op.f('ix_shipments_product'), 'shipments', ['product'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.create_table('shipment_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_logs_shipment_id'), 'shipment_logs', ['shipment_id'], unique=False)
    op.create_index('ix_shipment_logs_shipment_id_created_at', 'shipment_logs', ['shipment_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipment_logs_shipment_id_created_at', table_name='shipment_logs')
    op.drop_index(op.f('ix_shipment_logs_shipment_id'), table_name='shipment_logs')
    op.drop_table('shipment_logs')
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_product'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
